name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: source
        submodules: recursive

    - name: Step 1
      shell: bash
      run: |
        export TEST_ENV="Hello World"

    - name: Step 2
      shell: bash
      run: |
        printenv

    - name: Step 3
      shell: pwsh
      run: |
        Get-ChildItem env:

    - name: Step 4
      shell: bash
      run: |
        cd source
        mkdir build-1
        mkdir build-2
        pushd build-1
        export CC=gcc-11
        gcc --version
        cmake ..
        popd
        pushd build-2
        export CC=gcc-12
        gcc --version
        cmake ..
        popd
