name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Step 1
      shell: bash
      run: |
        export TEST_ENV="Hello World"

    - name: Step 2
      shell: bash
      run: |
        printenv
    
    - name: Step 3
      shell: pwsh
      run: |
        Get-ChildItem env:
    
    - name: Step 4
      shell: bash
      run: |
        ls
        ls ..
        mkdir build-1
        mkdir build-2
        pushd build-1
        CC=gcc-11
        gcc --version
        cmake ..
        popd
        pushd build-2
        CC=gcc-12
        gcc --version
        cmake ..
        popd
