name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-2022
    steps:

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.4.2
        arch: win64_msvc2019_64
        tools: ''

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.34
        vsversion: 2022

    - name: Setup Python Environment
      run: |
        pip install conan
        conan profile new default --detect
        conan install libiconv/1.17@ --build=missing
