name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-2022
    steps:

    - name: Setup Python Environment
      run: |
        pip install conan
        conan profile new default --detect
        conan install libiconv/1.17.0@ --build=missing
